### PR TITLE
Landingpage

### PR DESCRIPTION
**Pull request by arnav-khandelwal**
https://festive-davinci-741c16.netlify.com/?x=8&y=15
here is the link

### CODE REVIEW

**Comment by arnav-khandelwal** [comment]
landing page

**Review by sayamkanwar — CHANGES_REQUESTED** [review]
It shows "Not found" error!

**Comment by arnav-khandelwal** [comment]
https://optimistic-wing-754495.netlify.com/
fixed the problem
working now

**Review by sayamkanwar — CHANGES_REQUESTED** [review]
This is underdesigned, please work on the design!

**Comment by rchtgpt** [comment]
@arnav181104  Hey, if you are going to continue doing this task, I'd advise you to fix the prettier style violation and put indentation spaces between parent and child tags

**Pull request closed without merging**
