### PR TITLE
Create crawler

### PR DESCRIPTION
**Pull request by arjunkapoor19**
updated the things @sayamkanwar sir said please review the following

### CODE REVIEW

**Comment by ragasirtahk** [comment]
I am sorry but you still have not fixed all the coding standard violations as pointed out on: https://github.com/XINO-DPSR/open-source-marathon/pull/5

**Review by sayamkanwar — CHANGES_REQUESTED** [review]
Please fix the style violations in this code pointed out by @ragasirtahk (refer to the #5 )

**Comment by arjunkapoor19** [comment]
> Please fix the style violations in this code pointed out by @ragasirtahk (refer t

**Comment by arjunkapoor19** [comment]
> Please fix the style violations in this code pointed out by @ragasirtahk (refer to the #5 )
please grant my points for all my other activities(suggestion of name and tests for the crawler)
will get this done right away

**Pull request closed without merging**
